### ISSUE TITLE
Network blocks

### ISSUE THREAD

**Issue by SquidDev** [SquidDev-CC/CC-Tweaks#15]
- [x] Full block modem - ~~works like a peripheral proxy but connects directly to cables would be great.~~ This has been implemented as of #14. ~~It would be nice to have this without support for multipart, but that isn't a priority.~~ As of #22 
 - [x] ~~Wireless modem for wired networks - bind two wireless modems together and the two networks are one.~~ As of #20 
 - [x] ~~Wireless bridge peripheral & turtle upgrade. Uses the modem peripheral to emulate a wired network. I'm going to look into how possible it would be to use this with a turtle.~~  As of #22

**Comment by ElvishJerricco** [comment]
I'd be more interested in multipart modems. Like, a wireless modem that you stick on the cable directly. And wired modems that can be put on cables regardless of if the adjacent block is sold (solving the same problem that full block modems would solve).

**Comment by SquidDev** [comment]
I guess they could be full blocks or normal blocks. Because of how the network is implemented, the full block versions would allow you to chain blocks together without cables, like AE imlpements it. Maybe a full block and a multipart version of both of them would be nice.

**Comment by SquidDev** [comment]
Started work on #20. I guess the next step is a multipart equivalent of the wireless bridge and a non-multipart modem.

**Comment by SquidDev** [comment]
Implemented remaining bits in #22
